// =============================================================================
// VORTEX-OS — V4 Master Pipeline Dispatcher implementation
// =============================================================================
#include "DispatchV4.h"
#include "Hitl.h"
#include "Swarm.h"
#include "Inspector.h"
#include "PromptOptimizer.h"
#include "Commands.h"
#include "CostTracker.h"

namespace Vortex {

    bool DispatchV4::TaskIsHighStakes(Paths^ p, String^ taskId) {
        // Look in the plan.json for the task's high_stakes flag.
        // For the V4 supervisor.store flow the plan is generated by the
        // Shift Supervisor; for direct dispatches we treat the task as
        // high-stakes if the name starts with "package_" — same convention
        // the bash version uses for package_websim etc.
        if (taskId == nullptr) return false;
        return taskId->StartsWith("package_");
    }

    int DispatchV4::Run(Paths^ p, String^ taskId, String^ agentName, String^ objectiveRef) {
        // 1. GOVERNANCE PRE-CHECK
        if (TaskIsHighStakes(p, taskId)) {
            Hitl::YieldForApproval(p, taskId,
                "Agent " + agentName + " is requesting permission to execute an unverified high-stakes operational step.",
                "MODERATE");
            // YieldForApproval calls Environment::Exit(203) — we never reach here
            // unless the gate is bypassed.
            return 0;
        }

        // 2. HIERARCHICAL ROUTING
        if (agentName == "supervisor.store") {
            // In the bash version, jq reads the master objective from
            // tasks/${task_id}.json. With the objective_ref arg we can
            // skip that lookup.
            String^ masterObj = objectiveRef == nullptr ? "" : objectiveRef;
            Swarm::Spawn(p, taskId, masterObj);
            return 0;
        }

        // 3. STANDARD EXECUTION PASS (V3 hand-off)
        // The bash version reads a synthetic raw_output_${task_id}.json.
        // We mint a stub here so the rest of the pipeline has something
        // to inspect.
        String^ rawFile = Path::Combine(p->TmpDir, "raw_output_" + taskId + ".json");
        if (!File::Exists(rawFile)) {
            File::WriteAllText(rawFile, "{\"metrics\":{\"model\":\"MiniMax-Text-01\",\"tokens_in\":0,\"tokens_out\":0,\"duration_ms\":0}}");
        }
        JsonDocument^ raw = JsonX::ReadFile(rawFile);
        int runTokens = 0;
        int runTokensIn = 0;
        String^ runModel = "MiniMax-Text-01";
        int runDurationMs = 0;
        if (raw != nullptr && JsonX::Has(raw->RootElement, "metrics")) {
            JsonElement metrics = raw->RootElement.GetProperty("metrics");
            if (JsonX::Has(metrics, "tokens_out")) {
                JsonElement t = metrics.GetProperty("tokens_out");
                if (t.ValueKind == JsonValueKind::Number) runTokens = t.GetInt32();
            }
            if (JsonX::Has(metrics, "tokens_in")) {
                JsonElement t = metrics.GetProperty("tokens_in");
                if (t.ValueKind == JsonValueKind::Number) runTokensIn = t.GetInt32();
            }
            if (JsonX::Has(metrics, "model")) {
                JsonElement m = metrics.GetProperty("model");
                if (m.ValueKind == JsonValueKind::String) {
                    String^ mv = m.GetString();
                    if (!String::IsNullOrEmpty(mv)) runModel = mv;
                }
            }
            if (JsonX::Has(metrics, "duration_ms")) {
                JsonElement d = metrics.GetProperty("duration_ms");
                if (d.ValueKind == JsonValueKind::Number) runDurationMs = d.GetInt32();
            }
        }

        // 4. CROSS-CUTTING AUDIT
        if (!Inspector::InspectExecution(p, taskId, agentName, runTokens)) {
            return 1;
        }

        // 5. CONTINUITY ENFORCEMENT & SELF-HEALING
        if (!File::Exists(rawFile) || raw == nullptr) {
            PromptOptimizer::OptimizeAgent(p, agentName, "", "Failed to preserve critical system invariants or style guide.");
            return 1;
        }

        // 6. COST TRACKING (v0.1.10+) — record tokens + cost, check budget.
        // Pure file I/O; never fails the dispatch. Budget alerts surface as
        // PENDING_HUMAN gates via Hitl::YieldForApproval (Environment::Exit(203)).
        array<String^>^ tags = gcnew array<String^> { agentName, p->ProjectName };
        CostTracker::RecordTokens(p, taskId, agentName, p->ProjectName,
                                  runModel, runTokensIn, runTokens, runDurationMs, tags);
        CostTracker::CheckBudget(p, p->ProjectName, taskId);

        // 7. PIPELINE FINALIZATION
        // The bash version calls record_behavioral_fingerprint + finalize_task_state,
        // both of which are stubs in the original codebase. We log a final line.
        Console::WriteLine("V4_PIPELINE_OK task=" + taskId + " agent=" + agentName);
        return 0;
    }
}
